### PR TITLE
Add rd.xml for .NET Native compilation

### LINKED ISSUE #181: OpenXML not compiling in .NET Native
From @prairiesnpr on #168:

> I'm unable to compile in release mode with UWP. I receive an ILT0005 error. This is with VS2017RC and NETCore.UniversalWindowsPlatform 5.3.0. Get the same error with 2.7.1 or 2.7.2 -vnext0023. Remove OpenXml or compile in debug and the app will compile.

> Error is:
.nuget\packages\microsoft.net.native.compiler\1.6.0\tools\Microsoft.NetNative.targets(691,5): error : ILT0005: .nuget\packages\microsoft.net.native.compiler\1.6.0\tools\x64\ilc\Tools\nutc_driver.exe @"\obj\x64\Release\ilc\intermediate\MDIL\FirearmDb.rsp"' returned exit code 1

### PR DESCRIPTION
**Pull request by twsouthwick**
Fixes #181

### CODE REVIEW

**Comment by twsouthwick** [comment]
@mattwhilden I tried adding an rd.xml for the library per the discussion in #168, but when I add a UWP test project and try to compile it, it still fails with the ILC error. Am I doing something wrong when doing it in a library?

**Comment by MattWhilden** [comment]
Which version of Microsoft.NETCore.UniversalWindowsPlaftorm are you on?

**Comment by twsouthwick** [comment]
I'm using 5.4.0

**Comment by tomjebo** [comment]
@twsouthwick this may be a stupid question/observation but in DocumentFormat.OpenXml/DocumentFormat.OpenXml.csproj you specified "Properties\lib.rd.xml" but the filename is DocumentFormat.OpenXml/Properties/**Library**.rd.xml. But then I'm not sure I understand what you're doing here.

**Comment by twsouthwick** [comment]
@tomjebo good catch, but not the error here :(

**Comment by twsouthwick** [comment]
@MattWhilden I played around with this again tonight and it seems to be found. However, I'm getting `Out of Memory` errors:
```
2>  App1 -> C:\Users\twsou\Projects\Software\Open-XML-SDK\App1\bin\x64\Release\App1.exe
2>GENERATEPROJECTPRIFILE : warning PRI257: 0xdef00522 - Resources found for language(s) 'en' but no resources found for default language(s): 'en-US'. Change the default language or qualify resources with the default language. http://go.microsoft.com/fwlink/?LinkId=231899
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2015,5): warning APPX0104: Certificate file 'App1_TemporaryKey.pfx' not found.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2015,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
2>  Starting .NET Native compilation
2>  Processing application code
2>C:\Users\twsou\Projects\Software\Open-XML-SDK\App1\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
2>C:\Users\twsou\Projects\Software\Open-XML-SDK\App1\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
2>  Computing application closure and generating interop code
2>  Generating serialization code
2>  Compiling interop code
2>  Cleaning up unreferenced code
2>  Generating native code
2>STARTPROCESSTASK : error : Out of Memory
2>STARTPROCESSTASK : error : Out of Memory
2>STARTPROCESSTASK : error : Out of Memory
2>C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x64\ilc\IlcInternals.targets(1192,5): error : ILT0005: 'C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x64\ilc\Tools\nutc_driver.exe @"C:\Users\twsou\Projects\Software\Open-XML-SDK\App1\obj\x64\Release\ilc\intermediate\MDIL\App1.rsp"' returned exit code 1
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

Any thoughts? It was working earlier in the evening, but is failing now. I tried it with v6.0.1 of the tooling as well as 5.4.1 - fails on both. Using VS 15.4.2

**Comment by tomjebo** [comment]
@twsouthwick is this still pending resolution of the errors you were seeing?

**Comment by twsouthwick** [comment]
Yes, it is. Hoping to hear from someone from the .NET Native team on how to proceed.

**Comment by twsouthwick** [comment]
@tomjebo Once #301 is merged, this is unblocked.

**Pull request merged**
