### PR TITLE
East Asia is better term

### PR DESCRIPTION
**Pull request by davidchesnut**

### CODE REVIEW

**Comment by twsouthwick** [comment]
@davidchesnut You created the PR against master which was quite far behind vNext (the current dev branch). We are, however, in the process of moving to committing directly to master, so master is now up to date. However, your change must be updated before it can be merged.

**Comment by davidchesnut** [comment]
I'll resubmit on the vNext branch.

**Comment by twsouthwick** [comment]
@davidchesnut You actually submitted as I was switching our branching strategy. The vNext branch is no more. You can reopen this one and submit against master.

**Comment by twsouthwick** [comment]
Thanks! LGTM. We'll have to update the generator for this as well, but this will fix it for now.

**Pull request merged**
