### PR TITLE
[WIP] Build automation

### PR DESCRIPTION
**Pull request by sergey-tihon**
[Build status](https://ci.appveyor.com/project/sergey-tihon/open-xml-sdk/branch/vNext) [Build Status](https://travis-ci.org/sergey-tihon/Open-XML-SDK)

This PR contains:
- Migration to `xUnit 2.1`
- Single build script for win, linux and osx
- Travis CI execution matrix that run test on  (OSX & Linus)x(Mono Latest & Beta & Alpha & Nighly)
- Nuspec and automated nuget package creation.
- Latest 2.\* NuGet.exe

In order to release new version you need to
- Update `RELEASE_NOTES.md`
- Execute `build release`

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@EricWhiteDev Please merge #79  and #80 first and share your thought about this one.
Then I will rebase & cleanup this PR if required.

**Comment by japj** [comment]
Hello, what is the current status on this?

**Comment by sergey-tihon** [comment]
@japj I still wait any kind of response from maintainers about their plans about this repo.

**Comment by tomjebo** [comment]
@sergey-tihon we have a system in place for CI. you might want to rework this with the new build system for the cross platform aspects.

**Comment by resnyanskiy** [comment]
@tomjebo this PR contains "nuget package creation". If the package already created in another way, please give me a link to related info. If package not created, is there any plans to implement this feature? If there is no such plans, I suppose this PR should be reopened, reworked by author and then accepted.

**Comment by tomjebo** [comment]
@resnyanskiy Please refer to the readme for the repo. There are instructions to retrieve the nuget package there.

**Comment by resnyanskiy** [comment]
@tomjebo thank you very much 👍

**Pull request closed without merging**
