### PR TITLE
Added basic support for SVG files

### PR DESCRIPTION
**Pull request by mattiamerzi**
This patch allowed us to insert SVG files into a word document, adding support for "svgblip" element:
https://docs.microsoft.com/en-us/openspecs/office_standards/ms-odrawxml/2451f45e-5d77-4661-86d1-0a017fced779

### CODE REVIEW

**Comment by twsouthwick** [comment]
Thanks @mattiamerzi. Unfortunately, this change is in generated code that is currently not public. Can you open an issue to track this? For larger changes (or new functionality), please open an issue in the future so we can provide guidance on how to approach it?

**Comment by mattiamerzi** [comment]
> Thanks @mattiamerzi. Unfortunately, this change is in generated code that is currently not public. Can you open an issue to track this? For larger changes (or new functionality), please open an issue in the future so we can provide guidance on how to approach it?

Many thanks for your answer, @twsouthwick ; well, an issue has already been opened (and closed), it's #204 that you named "Add SVG as ImagePartType for Office 2016 support", it's dated back to 2017, and it's been automatically closed for inactivity.

What about reopening that issue?

**Comment by twsouthwick** [comment]
Ah, yes. Let's reopen that. I put a bot on to close inactive issues that ended up being too aggressive

**Comment by twsouthwick** [comment]
@mattiamerzi Thanks for this. We're working on updating the backend to generate this among other missing types. We'll try to keep it updated on the associated issue. For now, I'm going to close this issue.

**Pull request closed without merging**
