### PR TITLE
fix threadedcomments part code and documentation updates

### PR DESCRIPTION
**Pull request by tomjebo**
This adds the missing threadedcomments parts connection.

### CODE REVIEW

**Review by mcpgza — APPROVED** [review]
Seems ok

**Comment by tomjebo** [comment]
@mcpgza Thanks for bringing it to our attention. It looks like richdata will have a few types that have this issue as well so I'll work on getting a PR out in the next couple days.

**Comment by twsouthwick** [comment]
This will have to wait for a major version - we can do that, but FYI

**Comment by twsouthwick** [comment]
@tomjebo Can you separate out the doc updates from the threadedcomments? The doc updates can go in a near-term minor release as it doesn't affect the public API

**Review by twsouthwick — DISMISSED** [review]
Can you separate out the doc updates from the threadedcomments? The doc updates can go in a near-term patch release as it doesn't affect the public API

**Comment by tomjebo** [comment]
@twsouthwick  you took care of the doc comments so when this passes build, we're good to go for next minor build.

**Review by twsouthwick — APPROVED** [review]
LGTM. Let's wait to merge until after we ship 2.13.1

**Comment by twsouthwick** [comment]
@tomjebo This can now be merged :)

**Pull request merged**
