### PR TITLE
Add support for .NET 3.5, .NET 4.0, and .NET 4.6

### LINKED ISSUE #180: Add support for .NET 3.5
It appears that ClosedXML is holding off on taking a dependency on the latest versions because support for .NET 3.5 is dropped (see https://github.com/ClosedXML/ClosedXML/issues/225). Is there interest for a .NET 3.5 build of the library?

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds target frameworks for more .NET Framework versions, including
moving to .NET 4.6 instead of .NET 4.5. That way, .NET 4.6 and later can
use System.IO.Packaging, while frameworks below that will have access to
the library, but will use WindowsBase.

Fixes #180 and #174

### CODE REVIEW

**Comment by twsouthwick** [comment]
Looks like the `dotnet` tool doesn't understand .NET 3.5 reference assemblies. I'll look into switch things to msbuild as that does understand it.  See https://github.com/Microsoft/msbuild/issues/1333

**Comment by ThomasBarnekow** [comment]
I assume that does not impact people targeting 4.5.x in any way, right?

On a somewhat related note, does anybody know whether there are .NET Framework "deployment statistics". For example, the question is what percentage of corporate desktop PCs have .NET Framework 4.6.x installed.

Google provides information regarding the percentage of Android devices using which Android release, so you can decide which one you would want to target in order to capture whatever percentage of the market.

**Comment by twsouthwick** [comment]
@ThomasBarnekow, this won't affect 4.5.x in any way. However, if you target 4.6, you'll get the updated `System.IO.Packaging` that has a few fixes that are not in the `WindowsBase` version of the packaging tools.

**Comment by HollyAM** [comment]
@ThomasBarnekow, 
.NET 4.6 or a greater version is present on all win10 machines, so you can count on them being on over 300 Million active devices: https://blogs.windows.com/windowsexperience/2016/05/05/windows-10-now-on-300-million-active-devices-free-upgrade-offer-to-end-soon/

They are also present on other OSes windows 7 or greater. We don't typically make those numbers public, but if you can explain your need more specifically, I might be able to provide more details.

**Comment by ThomasBarnekow** [comment]
@HollyAM, thanks for responding. I will contact you by email to explain what I would need to know.

**Comment by twsouthwick** [comment]
@tomjebo This is ready to review. Thanks!

**Comment by tomjebo** [comment]
@twsouthwick sorry I didn't get to this until now. I decided to leave the two commits separate as they seemed to be logically independent enough. Hope that's ok with you. Thanks for straightening all of this out.

**Pull request merged**
