### PR TITLE
Code cleanup - introducing the 'nameof' operator instead of string values

### PR DESCRIPTION
**Pull request by mkorsukov**
- The changes were done in DocumentFormat.OpenXml project
- Simple replacement for basic scenarios like throwing an exception
- No logic code change

### CODE REVIEW

**Comment by mkorsukov** [comment]
Contribution license agreement was signed!

**Comment by twsouthwick** [comment]
@mkorsukov Can you try again? It should automatically update the tag after the process is completed.

**Comment by mkorsukov** [comment]
@twsouthwick I submitted MS CLA again.

**Comment by twsouthwick** [comment]
Thanks! We'll look into why the CLA tag isn't being updated.

**Comment by msftgits** [comment]
Working around a CLA webhook issue by closing & re-opening this pull request. Thanks for your contribution.

**Comment by tomjebo** [comment]
@mkorsukov merged the nameof changes. Thank you for the cleanup contribution!

**Pull request merged**
